INC="/home/adm1n/Shop/googletest/googletest/include/gtest"


install:
	g++ -pthread -lgtest_main  -lgtest -lpthread test/test_binary_tree.cc src/binary_tree.cc -I $(INC) -o binary_tree_test.o

clean:
	rm *.o
